#include "Token.h"

std::string tokenTypeToString(TokenType type) {
  switch (type) {
  case TokenType::INT:
    return "INT";
  case TokenType::FLOAT:
    return "FLOAT";
  case TokenType::DOUBLE:
    return "DOUBLE";
  case TokenType::CHAR:
    return "CHAR";
  case TokenType::VOID:
    return "VOID";
  case TokenType::BOOL:
    return "BOOL";
  case TokenType::RETURN:
    return "RETURN";
  case TokenType::IF:
    return "IF";
  case TokenType::ELSE:
    return "ELSE";
  case TokenType::WHILE:
    return "WHILE";
  case TokenType::FOR:
    return "FOR";
  case TokenType::DO:
    return "DO";
  case TokenType::CLASS:
    return "CLASS";
  case TokenType::PUBLIC:
    return "PUBLIC";
  case TokenType::PRIVATE:
    return "PRIVATE";
  case TokenType::PROTECTED:
    return "PROTECTED";
  case TokenType::TRUE_LITERAL:
    return "TRUE_LITERAL";
  case TokenType::FALSE_LITERAL:
    return "FALSE_LITERAL";
  case TokenType::IDENTIFIER:
    return "IDENTIFIER";
  case TokenType::NUMBER_INT:
    return "NUMBER_INT";
  case TokenType::NUMBER_FLOAT:
    return "NUMBER_FLOAT";
  case TokenType::STRING_LITERAL:
    return "STRING_LITERAL";
  case TokenType::CHAR_LITERAL:
    return "CHAR_LITERAL";
  case TokenType::EQUALS:
    return "EQUALS";
  case TokenType::EQUALS_EQUALS:
    return "EQUALS_EQUALS";
  case TokenType::BANG:
    return "BANG";
  case TokenType::BANG_EQUALS:
    return "BANG_EQUALS";
  case TokenType::LESS:
    return "LESS";
  case TokenType::LESS_EQUALS:
    return "LESS_EQUALS";
  case TokenType::LESS_LESS:
    return "LESS_LESS";
  case TokenType::GREATER:
    return "GREATER";
  case TokenType::GREATER_EQUALS:
    return "GREATER_EQUALS";
  case TokenType::GREATER_GREATER:
    return "GREATER_GREATER";
  case TokenType::PLUS:
    return "PLUS";
  case TokenType::PLUS_PLUS:
    return "PLUS_PLUS";
  case TokenType::PLUS_EQUALS:
    return "PLUS_EQUALS";
  case TokenType::MINUS:
    return "MINUS";
  case TokenType::MINUS_MINUS:
    return "MINUS_MINUS";
  case TokenType::MINUS_EQUALS:
    return "MINUS_EQUALS";
  case TokenType::STAR:
    return "STAR";
  case TokenType::STAR_EQUALS:
    return "STAR_EQUALS";
  case TokenType::SLASH:
    return "SLASH";
  case TokenType::SLASH_EQUALS:
    return "SLASH_EQUALS";
  case TokenType::PERCENT:
    return "PERCENT";
  case TokenType::AMPERSAND:
    return "AMPERSAND";
  case TokenType::AMPERSAND_AMPERSAND:
    return "AMPERSAND_AMPERSAND";
  case TokenType::PIPE:
    return "PIPE";
  case TokenType::PIPE_PIPE:
    return "PIPE_PIPE";
  case TokenType::SEMICOLON:
    return "SEMICOLON";
  case TokenType::COLON:
    return "COLON";
  case TokenType::COMMA:
    return "COMMA";
  case TokenType::DOT:
    return "DOT";
  case TokenType::LPAREN:
    return "LPAREN";
  case TokenType::RPAREN:
    return "RPAREN";
  case TokenType::LBRACE:
    return "LBRACE";
  case TokenType::RBRACE:
    return "RBRACE";
  case TokenType::LBRACKET:
    return "LBRACKET";
  case TokenType::RBRACKET:
    return "RBRACKET";
  case TokenType::EOF_TOK:
    return "EOF";
  case TokenType::UNKNOWN:
    return "UNKNOWN";
  default:
    return "UNKNOWN";
  }
}
